export const listSellerProps = [
  {
    propID: 1,
    propImg:
      "https://i.pinimg.com/564x/29/06/66/2906662076e6deca9cfecee295099cff.jpg",
    imgList: 10,
    propType: "villa",
    desc: "REO Occupied - the seller does not represent or guarantee occupancy status. NO VIEWINGS of this property. Please DO NOT DISTURB the occupant. Buyer will be responsible of obtaining possession of the property upon closing",
    propAddress: "11314 MAPLE GROVE LNTrumann, AR 72472",
    beds: 2,
    baths: 3,
    area: 5960,
    status: "IN AUCTION",
  },
  {
    propID: 2,
    propImg:
      "https://i.pinimg.com/564x/29/06/66/2906662076e6deca9cfecee295099cff.jpg",
    imgList: 8,
    propType: "apartment",
    desc: "REO Occupied - the seller does not represent or guarantee occupancy status. NO VIEWINGS of this property. Please DO NOT DISTURB the occupant. Buyer will be responsible of obtaining possession of the property upon closing",
    propAddress: "225 PINE STREET Apt 5BNewark, NJ 07105",
    beds: 2,
    baths: 3,
    area: 5960,
    status: "PENDING",
  },
  {
    propID: 3,
    propImg:
      "https://i.pinimg.com/564x/29/06/66/2906662076e6deca9cfecee295099cff.jpg",
    imgList: 12,
    propType: "condo",
    desc: "REO Occupied - the seller does not represent or guarantee occupancy status. NO VIEWINGS of this property. Please DO NOT DISTURB the occupant. Buyer will be responsible of obtaining possession of the property upon closing",
    propAddress: "789 OAK AVENUE Apt 304San Francisco, CA 94103",
    beds: 2,
    baths: 3,
    area: 5960,
    status: "SOLD",
  },
  {
    propID: 4,
    propImg:
      "https://i.pinimg.com/564x/29/06/66/2906662076e6deca9cfecee295099cff.jpg",
    imgList: 15,
    propType: "townhouse",
    desc: "REO Occupied - the seller does not represent or guarantee occupancy status. NO VIEWINGS of this property. Please DO NOT DISTURB the occupant. Buyer will be responsible of obtaining possession of the property upon closing",
    propAddress: "456 CEDAR LANE UNIT 8BHouston, TX 77002",
    beds: 2,
    baths: 3,
    area: 5960,
    status: "AVAILABLE",
  },
  {
    propID: 5,
    propImg:
      "https://i.pinimg.com/564x/29/06/66/2906662076e6deca9cfecee295099cff.jpg",
    imgList: 15,
    propType: "Residential Land",
    desc: "REO Occupied - the seller does not represent or guarantee occupancy status. NO VIEWINGS of this property. Please DO NOT DISTURB the occupant. Buyer will be responsible of obtaining possession of the property upon closing",
    propAddress: "456 CEDAR LANE UNIT 8BHouston, TX 77002",
    beds: 2,
    baths: 3,
    area: 5960,
    status: "REJECTED",
  },
  {
    propID: 6,
    propImg:
      "https://i.pinimg.com/564x/29/06/66/2906662076e6deca9cfecee295099cff.jpg",
    imgList: 15,
    propType: "townhouse",
    desc: "REO Occupied - the seller does not represent or guarantee occupancy status. NO VIEWINGS of this property. Please DO NOT DISTURB the occupant. Buyer will be responsible of obtaining possession of the property upon closing",
    propAddress: "456 CEDAR LANE UNIT 8BHouston, TX 77002",
    beds: 2,
    baths: 3,
    area: 5960,
    status: "REJECTED",
  },
];
