export const propertyTypes = [
  "Villa",
  "Condominium",
  "Apartment",
  "Townhouse",
  "Duplex",
  "Office Space",
  "Retail Space",
  "Warehouse",
  "Restaurant",
  "Residential Land",
  "Commercial Land",
  "Hotel",
  "Resort",
  "School/College",
  "Hospital",
  "Factory",
  "Industrial Land",
  "Beachfront Home",
  "Mountain Cabin",
  "Vacation Rental",
  "Rental Property",
  "Fixer-Upper",
  "Foreclosed Home",
  "Island",
];
