export const auctionProp = [
  {
    propID: 1,
    propImg:
      "https://i.pinimg.com/564x/29/06/66/2906662076e6deca9cfecee295099cff.jpg",
    imgList: 10,
    propType: "villa",
    name: "Nguyen Duy Tan Hung",
    propAddress: "11314 MAPLE GROVE LNTrumann, AR 72472",
    days: 1,
    hours: 0,
    mins: 0,
    secs: 10,
    yourBid: 20000,
    currentBid: 200000,
    isFav: true,
    beds: 2,
    baths: 3,
    area: 5960,
    desc: "REO Occupied - the seller does not represent or guarantee occupancy status. NO VIEWINGS of this property. Please DO NOT DISTURB the occupant. Buyer will be responsible of obtaining possession of the property upon closing",
  },
  {
    propID: 2,
    propImg:
      "https://i.pinimg.com/564x/29/06/66/2906662076e6deca9cfecee295099cff.jpg",
    imgList: 8,
    propType: "apartment",
    name: "Sophie Johnson",
    propAddress: "225 PINE STREET Apt 5BNewark, NJ 07105",
    days: 5,
    hours: 2,
    mins: 30,
    secs: 15,
    yourBid: 18000,
    currentBid: 18000,
    isFav: true,
    beds: 2,
    baths: 3,
    area: 5960,
    desc: "REO Occupied - the seller does not represent or guarantee occupancy status. NO VIEWINGS of this property. Please DO NOT DISTURB the occupant. Buyer will be responsible of obtaining possession of the property upon closing",
  },
  {
    propID: 3,
    propImg:
      "https://i.pinimg.com/564x/29/06/66/2906662076e6deca9cfecee295099cff.jpg",
    imgList: 12,
    propType: "condo",
    name: "Alex Rodriguez",
    propAddress: "789 OAK AVENUE Apt 304San Francisco, CA 94103",
    days: 7,
    hours: 1,
    mins: 45,
    secs: 30,
    yourBid: 25000,
    currentBid: 30000,
    isFav: false,
    beds: 2,
    baths: 3,
    area: 5960,
    desc: "REO Occupied - the seller does not represent or guarantee occupancy status. NO VIEWINGS of this property. Please DO NOT DISTURB the occupant. Buyer will be responsible of obtaining possession of the property upon closing",
  },
];
